idf_component_register(SRCS "fullsize_signals.cpp"
                       INCLUDE_DIRS "include"
                       EMBED_FILES "data/translation_signal_left_45900.bin"
                                   "data/translation_signal_right_45900.bin"
                                   "data/rotation_signal_left_45900.bin"
                                   "data/rotation_signal_right_45900.bin")
